#!/bin/bash

#SBATCH --output=out/slurm_output_%A.out
#SBATCH --job-name=SnelliusRun
#SBATCH --mem=32G
#SBATCH --cpus-per-task=4
#SBATCH --time=2:00:00
#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --output=out/slurm_output_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

export PYTHONPATH="${PYTHONPATH}:./"
source activate uva-ir2
srun python scripts/inversion_attacks.py runs/attack.yaml
