model_name: sentence-transformers/gtr-t5-base
corrector_name: gtr-base
dataset: scifact
dataset_list : [
  "arguana",
  "fiqa",
  "nfcorpus",
  "quora",
  "scifact",
  "vihealthqa",
]
quantize_list : [
  "naive-8-bit",
  "zero_point",
  "nothing",
]
batch_size: 64
max_seq_length: 32
num_steps: 20
max_samples: 50
max_querry_samples: 1000
add_gaussian_noise: False
noise_mean: 0
noise_std: 1
noise_lambda: [1, 0.1, 0.01, 0.001]
sequence_beam_width: 0
export_path: "out/results_quant_6.pickle"
quantize: True