model_name: sentence-transformers/gtr-t5-base
corrector_name: gtr-base
dataset: scifact
dataset_list : [
  "arguana",
  "fiqa",
  "nfcorpus",
  "quora",
  "scifact",
]
batch_size: 64
num_steps: 20
max_samples: 50
max_seq_length: 32
max_querry_samples: 1000
add_gaussian_noise: True
noise_mean: 0
noise_std: 1
noise_lambda: [1, 0.1, 0.01, 0.001, 0]
sequence_beam_width: 0
export_path: "out/results_6.pickle"
