model_name: sentence-transformers/gtr-t5-base
corrector_name: gtr-base
dataset: scifact
batch_size: 64
num_steps: 20
max_samples: 100
add_gaussian_noise: True
noise_std: 0
noise_lambda: 1
noise_lambda: 0
