# Smaller batch size (128->16) to avoid OOM for Snellius, decreased max_samples to (1000->100) to speed up the experiment
model_name: sentence-transformers/gtr-t5-base
corrector_name: gtr-base
dataset: nq
batch_size: 4
num_steps: 50
max_samples: 100
max_seq_length: 32
sequence_beam_width: 8
